# Generated by Django 5.2.4 on 2025-07-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
