# Generated by Django 5.1.7 on 2025-07-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_articulo_esta_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
