# Generated by Django 5.1.7 on 2025-07-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_articulo_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='market.mensaje'),
        ),
    ]
