# Generated by Django 5.1.7 on 2025-07-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_mensaje_mensaje_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_articulos/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='market.articulo')),
            ],
        ),
    ]
